import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, FlatList, Dimensions, ActivityIndicator, ScrollView, SafeAreaView, TouchableOpacity, Share, Alert } from 'react-native';
import { LineChart, PieChart } from 'react-native-chart-kit';
import api from '../api/axiosConfig';

const MOOD_COLORS = {
  Happy: '#4ade80', Calm: '#60a5fa', Sad: '#94a3b8', 
  Anxious: '#fb923c', Angry: '#f87171', Tired: '#c084fc'
};

export default function MoodHistoryScreen({ navigation }) {
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchLogs();
    navigation.setOptions({
      headerLeft: () => (
        <TouchableOpacity onPress={() => navigation.navigate('Dashboard')} style={{marginLeft: 15}}>
          <Text style={{fontSize: 20}}>🏠</Text>
        </TouchableOpacity>
      ),
      headerRight: () => (
        <TouchableOpacity onPress={handleExport} style={{marginRight: 15}}>
          <Text style={{fontSize: 14, fontWeight: 'bold', color: '#0f766e'}}>Export 📄</Text>
        </TouchableOpacity>
      )
    });
  }, [logs]);

  const fetchLogs = async () => {
    try {
      const res = await api.get('/moods');
      setLogs(res.data);
    } catch (e) {
      console.log('Failed to fetch logs', e);
    }
    setLoading(false);
  };

  const handleExport = async () => {
    if (logs.length === 0) {
      Alert.alert('No Data', 'You need mood logs to generate a report.');
      return;
    }
    
    const stats = getStats();
    let report = `CLINICAL MOOD REPORT\nGenerated: ${new Date().toLocaleString()}\n\n`;
    report += `Summary:\n- Total Logs: ${logs.length}\n- Average Intensity: ${stats.avgIntensity}/10\n\n`;
    report += `Recent History:\n`;
    logs.slice(0, 10).forEach(l => {
      report += `- ${new Date(l.createdAt).toLocaleDateString()}: ${l.mood} (${l.intensity}/10)\n`;
    });
    report += `\nThis report was generated by AI Healthcare Assistant. Please share this with your doctor for better clinical insights.`;

    try {
      await Share.share({ message: report, title: 'My Mental Health Report' });
    } catch (e) {
      console.log('Export failed', e);
    }
  };

  const getStats = () => {
    if (logs.length === 0) return null;
    const moodCounts = {};
    logs.forEach(l => moodCounts[l.mood] = (moodCounts[l.mood] || 0) + 1);
    
    const pieData = Object.keys(moodCounts).map(mood => ({
      name: mood,
      population: moodCounts[mood],
      color: MOOD_COLORS[mood] || '#ccc',
      legendFontColor: '#475569',
      legendFontSize: 12
    }));

    const avgIntensity = (logs.reduce((acc, l) => acc + l.intensity, 0) / logs.length).toFixed(1);

    return { pieData, avgIntensity };
  };

  const stats = getStats();

  if (loading) return <View style={styles.centered}><ActivityIndicator size="large" color="#0f766e" /></View>;

  return (
    <SafeAreaView style={styles.safe}>
      <ScrollView style={styles.container} contentContainerStyle={{paddingBottom: 40}}>
        <Text style={styles.mainTitle}>Mood Analytics</Text>

        {logs.length === 0 ? (
          <View style={styles.emptyCard}>
            <Text style={{fontSize: 50, marginBottom: 10}}>📊</Text>
            <Text style={styles.emptyText}>No data yet. Log your first mood to see stats!</Text>
          </View>
        ) : (
          <>
            <View style={styles.summaryRow}>
              <View style={styles.summaryCard}>
                <Text style={styles.summaryLabel}>Total Logs</Text>
                <Text style={styles.summaryValue}>{logs.length}</Text>
              </View>
              <View style={[styles.summaryCard, { backgroundColor: '#ccfbf1' }]}>
                <Text style={styles.summaryLabel}>Avg Intensity</Text>
                <Text style={[styles.summaryValue, { color: '#0f766e' }]}>{stats.avgIntensity}</Text>
              </View>
            </View>

            <View style={styles.chartSection}>
              <Text style={styles.sectionTitle}>Mood Distribution</Text>
              <PieChart
                data={stats.pieData}
                width={Dimensions.get('window').width - 40}
                height={200}
                chartConfig={{ color: (opacity = 1) => `rgba(0, 0, 0, ${opacity})` }}
                accessor="population"
                backgroundColor="transparent"
                paddingLeft="15"
                absolute
              />
            </View>

            <View style={styles.chartSection}>
              <Text style={styles.sectionTitle}>Recent Trend</Text>
              {logs.length >= 2 ? (
                <LineChart
                  data={{
                    labels: [...logs].slice(0, 5).reverse().map(l => new Date(l.createdAt).toLocaleDateString([], {day: 'numeric', month: 'short'})),
                    datasets: [{ data: [...logs].slice(0, 5).reverse().map(l => l.intensity) }]
                  }}
                  width={Dimensions.get('window').width - 40}
                  height={180}
                  chartConfig={{
                    backgroundGradientFrom: '#fff',
                    backgroundGradientTo: '#fff',
                    decimalPlaces: 0,
                    color: (opacity = 1) => `rgba(15, 118, 110, ${opacity})`,
                    labelColor: (opacity = 1) => `rgba(100, 116, 139, ${opacity})`,
                    style: { borderRadius: 16 },
                    propsForDots: { r: '4', strokeWidth: '2', stroke: '#0f766e' }
                  }}
                  bezier
                  style={{ marginVertical: 8, borderRadius: 16 }}
                />
              ) : (
                <Text style={styles.miniText}>Log more moods to see your line chart.</Text>
              )}
            </View>

            <Text style={styles.sectionTitle}>Recent Logs</Text>
            {logs.slice(0, 5).map(item => (
              <View key={item._id} style={styles.logCard}>
                <View style={{flexDirection: 'row', justifyContent: 'space-between'}}>
                  <Text style={[styles.logMood, { color: MOOD_COLORS[item.mood] || '#333' }]}>{item.mood} • {item.intensity}/10</Text>
                  <Text style={styles.logDate}>{new Date(item.createdAt).toLocaleDateString()}</Text>
                </View>
                {item.notes ? <Text style={styles.logNotes}>{item.notes}</Text> : null}
              </View>
            ))}
          </>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#f8fafc' },
  container: { flex: 1, padding: 20 },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  mainTitle: { fontSize: 26, fontWeight: 'bold', color: '#1e293b', marginBottom: 20 },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  summaryCard: { width: '48%', backgroundColor: '#fff', padding: 15, borderRadius: 16, elevation: 2, shadowColor: '#000', shadowOpacity: 0.05 },
  summaryLabel: { fontSize: 12, color: '#64748b', marginBottom: 5 },
  summaryValue: { fontSize: 24, fontWeight: 'bold', color: '#1e293b' },
  chartSection: { backgroundColor: '#fff', padding: 15, borderRadius: 16, marginBottom: 20, elevation: 2, shadowColor: '#000', shadowOpacity: 0.05 },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', color: '#1e293b', marginBottom: 15 },
  emptyCard: { alignItems: 'center', marginTop: 50 },
  emptyText: { color: '#64748b', textAlign: 'center', fontSize: 16 },
  miniText: { color: '#94a3b8', textAlign: 'center', padding: 20 },
  logCard: { backgroundColor: '#fff', padding: 15, borderRadius: 12, marginBottom: 12, borderLeftWidth: 4, borderLeftColor: '#f1f5f9' },
  logMood: { fontSize: 15, fontWeight: 'bold' },
  logDate: { fontSize: 12, color: '#94a3b8' },
  logNotes: { marginTop: 5, fontSize: 13, color: '#64748b', fontStyle: 'italic' }
});
